// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CSceneObjectChange.proto

#include "CSceneObjectChange.pb.h"

#include <algorithm>

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

PROTOBUF_PRAGMA_INIT_SEG
namespace tdrp {
namespace packet {
constexpr CSceneObjectChange_Attribute::CSceneObjectChange_Attribute(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : id_(0u)
  , _oneof_case_{}{}
struct CSceneObjectChange_AttributeDefaultTypeInternal {
  constexpr CSceneObjectChange_AttributeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CSceneObjectChange_AttributeDefaultTypeInternal() {}
  union {
    CSceneObjectChange_Attribute _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CSceneObjectChange_AttributeDefaultTypeInternal _CSceneObjectChange_Attribute_default_instance_;
constexpr CSceneObjectChange::CSceneObjectChange(
  ::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized)
  : properties_()
  , attributes_()
  , id_(0u){}
struct CSceneObjectChangeDefaultTypeInternal {
  constexpr CSceneObjectChangeDefaultTypeInternal()
    : _instance(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized{}) {}
  ~CSceneObjectChangeDefaultTypeInternal() {}
  union {
    CSceneObjectChange _instance;
  };
};
PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT CSceneObjectChangeDefaultTypeInternal _CSceneObjectChange_default_instance_;
}  // namespace packet
}  // namespace tdrp
static ::PROTOBUF_NAMESPACE_ID::Metadata file_level_metadata_CSceneObjectChange_2eproto[2];
static constexpr ::PROTOBUF_NAMESPACE_ID::EnumDescriptor const** file_level_enum_descriptors_CSceneObjectChange_2eproto = nullptr;
static constexpr ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor const** file_level_service_descriptors_CSceneObjectChange_2eproto = nullptr;

const ::PROTOBUF_NAMESPACE_ID::uint32 TableStruct_CSceneObjectChange_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange_Attribute, _internal_metadata_),
  ~0u,  // no _extensions_
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange_Attribute, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange_Attribute, id_),
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  ::PROTOBUF_NAMESPACE_ID::internal::kInvalidFieldOffsetTag,
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange_Attribute, value_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange, id_),
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange, properties_),
  PROTOBUF_FIELD_OFFSET(::tdrp::packet::CSceneObjectChange, attributes_),
};
static const ::PROTOBUF_NAMESPACE_ID::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tdrp::packet::CSceneObjectChange_Attribute)},
  { 12, -1, sizeof(::tdrp::packet::CSceneObjectChange)},
};

static ::PROTOBUF_NAMESPACE_ID::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tdrp::packet::_CSceneObjectChange_Attribute_default_instance_),
  reinterpret_cast<const ::PROTOBUF_NAMESPACE_ID::Message*>(&::tdrp::packet::_CSceneObjectChange_default_instance_),
};

const char descriptor_table_protodef_CSceneObjectChange_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) =
  "\n\030CSceneObjectChange.proto\022\013tdrp.packet\""
  "\244\002\n\022CSceneObjectChange\022\n\n\002id\030\001 \001(\007\022=\n\npr"
  "operties\030\002 \003(\0132).tdrp.packet.CSceneObjec"
  "tChange.Attribute\022=\n\nattributes\030\003 \003(\0132)."
  "tdrp.packet.CSceneObjectChange.Attribute"
  "\032\203\001\n\tAttribute\022\n\n\002id\030\001 \001(\r\022\020\n\006as_int\030\002 \001"
  "(\003H\000\022\021\n\007as_uint\030\003 \001(\004H\000\022\022\n\010as_float\030\004 \001("
  "\002H\000\022\023\n\tas_double\030\005 \001(\001H\000\022\023\n\tas_string\030\006 "
  "\001(\tH\000B\007\n\005valueb\006proto3"
  ;
static ::PROTOBUF_NAMESPACE_ID::internal::once_flag descriptor_table_CSceneObjectChange_2eproto_once;
const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_CSceneObjectChange_2eproto = {
  false, false, 342, descriptor_table_protodef_CSceneObjectChange_2eproto, "CSceneObjectChange.proto", 
  &descriptor_table_CSceneObjectChange_2eproto_once, nullptr, 0, 2,
  schemas, file_default_instances, TableStruct_CSceneObjectChange_2eproto::offsets,
  file_level_metadata_CSceneObjectChange_2eproto, file_level_enum_descriptors_CSceneObjectChange_2eproto, file_level_service_descriptors_CSceneObjectChange_2eproto,
};
PROTOBUF_ATTRIBUTE_WEAK ::PROTOBUF_NAMESPACE_ID::Metadata
descriptor_table_CSceneObjectChange_2eproto_metadata_getter(int index) {
  ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&descriptor_table_CSceneObjectChange_2eproto);
  return descriptor_table_CSceneObjectChange_2eproto.file_level_metadata[index];
}

// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY static ::PROTOBUF_NAMESPACE_ID::internal::AddDescriptorsRunner dynamic_init_dummy_CSceneObjectChange_2eproto(&descriptor_table_CSceneObjectChange_2eproto);
namespace tdrp {
namespace packet {

// ===================================================================

class CSceneObjectChange_Attribute::_Internal {
 public:
};

CSceneObjectChange_Attribute::CSceneObjectChange_Attribute(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tdrp.packet.CSceneObjectChange.Attribute)
}
CSceneObjectChange_Attribute::CSceneObjectChange_Attribute(const CSceneObjectChange_Attribute& from)
  : ::PROTOBUF_NAMESPACE_ID::Message() {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_ = from.id_;
  clear_has_value();
  switch (from.value_case()) {
    case kAsInt: {
      _internal_set_as_int(from._internal_as_int());
      break;
    }
    case kAsUint: {
      _internal_set_as_uint(from._internal_as_uint());
      break;
    }
    case kAsFloat: {
      _internal_set_as_float(from._internal_as_float());
      break;
    }
    case kAsDouble: {
      _internal_set_as_double(from._internal_as_double());
      break;
    }
    case kAsString: {
      _internal_set_as_string(from._internal_as_string());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:tdrp.packet.CSceneObjectChange.Attribute)
}

void CSceneObjectChange_Attribute::SharedCtor() {
id_ = 0u;
clear_has_value();
}

CSceneObjectChange_Attribute::~CSceneObjectChange_Attribute() {
  // @@protoc_insertion_point(destructor:tdrp.packet.CSceneObjectChange.Attribute)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CSceneObjectChange_Attribute::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
  if (has_value()) {
    clear_value();
  }
}

void CSceneObjectChange_Attribute::ArenaDtor(void* object) {
  CSceneObjectChange_Attribute* _this = reinterpret_cast< CSceneObjectChange_Attribute* >(object);
  (void)_this;
}
void CSceneObjectChange_Attribute::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CSceneObjectChange_Attribute::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CSceneObjectChange_Attribute::clear_value() {
// @@protoc_insertion_point(one_of_clear_start:tdrp.packet.CSceneObjectChange.Attribute)
  switch (value_case()) {
    case kAsInt: {
      // No need to clear
      break;
    }
    case kAsUint: {
      // No need to clear
      break;
    }
    case kAsFloat: {
      // No need to clear
      break;
    }
    case kAsDouble: {
      // No need to clear
      break;
    }
    case kAsString: {
      value_.as_string_.Destroy(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArena());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = VALUE_NOT_SET;
}


void CSceneObjectChange_Attribute::Clear() {
// @@protoc_insertion_point(message_clear_start:tdrp.packet.CSceneObjectChange.Attribute)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  id_ = 0u;
  clear_value();
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CSceneObjectChange_Attribute::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // uint32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 8)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::ReadVarint32(&ptr);
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // int64 as_int = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 16)) {
          _internal_set_as_int(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // uint64 as_uint = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 24)) {
          _internal_set_as_uint(::PROTOBUF_NAMESPACE_ID::internal::ReadVarint64(&ptr));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      // float as_float = 4;
      case 4:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 37)) {
          _internal_set_as_float(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<float>(ptr));
          ptr += sizeof(float);
        } else goto handle_unusual;
        continue;
      // double as_double = 5;
      case 5:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 41)) {
          _internal_set_as_double(::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<double>(ptr));
          ptr += sizeof(double);
        } else goto handle_unusual;
        continue;
      // string as_string = 6;
      case 6:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 50)) {
          auto str = _internal_mutable_as_string();
          ptr = ::PROTOBUF_NAMESPACE_ID::internal::InlineGreedyStringParser(str, ptr, ctx);
          CHK_(::PROTOBUF_NAMESPACE_ID::internal::VerifyUTF8(str, "tdrp.packet.CSceneObjectChange.Attribute.as_string"));
          CHK_(ptr);
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CSceneObjectChange_Attribute::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tdrp.packet.CSceneObjectChange.Attribute)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt32ToArray(1, this->_internal_id(), target);
  }

  // int64 as_int = 2;
  if (_internal_has_as_int()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteInt64ToArray(2, this->_internal_as_int(), target);
  }

  // uint64 as_uint = 3;
  if (_internal_has_as_uint()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteUInt64ToArray(3, this->_internal_as_uint(), target);
  }

  // float as_float = 4;
  if (_internal_has_as_float()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFloatToArray(4, this->_internal_as_float(), target);
  }

  // double as_double = 5;
  if (_internal_has_as_double()) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteDoubleToArray(5, this->_internal_as_double(), target);
  }

  // string as_string = 6;
  if (_internal_has_as_string()) {
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(
      this->_internal_as_string().data(), static_cast<int>(this->_internal_as_string().length()),
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::SERIALIZE,
      "tdrp.packet.CSceneObjectChange.Attribute.as_string");
    target = stream->WriteStringMaybeAliased(
        6, this->_internal_as_string(), target);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tdrp.packet.CSceneObjectChange.Attribute)
  return target;
}

size_t CSceneObjectChange_Attribute::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tdrp.packet.CSceneObjectChange.Attribute)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // uint32 id = 1;
  if (this->id() != 0) {
    total_size += 1 +
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt32Size(
        this->_internal_id());
  }

  switch (value_case()) {
    // int64 as_int = 2;
    case kAsInt: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::Int64Size(
          this->_internal_as_int());
      break;
    }
    // uint64 as_uint = 3;
    case kAsUint: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::UInt64Size(
          this->_internal_as_uint());
      break;
    }
    // float as_float = 4;
    case kAsFloat: {
      total_size += 1 + 4;
      break;
    }
    // double as_double = 5;
    case kAsDouble: {
      total_size += 1 + 8;
      break;
    }
    // string as_string = 6;
    case kAsString: {
      total_size += 1 +
        ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::StringSize(
          this->_internal_as_string());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CSceneObjectChange_Attribute::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tdrp.packet.CSceneObjectChange.Attribute)
  GOOGLE_DCHECK_NE(&from, this);
  const CSceneObjectChange_Attribute* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CSceneObjectChange_Attribute>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tdrp.packet.CSceneObjectChange.Attribute)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tdrp.packet.CSceneObjectChange.Attribute)
    MergeFrom(*source);
  }
}

void CSceneObjectChange_Attribute::MergeFrom(const CSceneObjectChange_Attribute& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tdrp.packet.CSceneObjectChange.Attribute)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
  switch (from.value_case()) {
    case kAsInt: {
      _internal_set_as_int(from._internal_as_int());
      break;
    }
    case kAsUint: {
      _internal_set_as_uint(from._internal_as_uint());
      break;
    }
    case kAsFloat: {
      _internal_set_as_float(from._internal_as_float());
      break;
    }
    case kAsDouble: {
      _internal_set_as_double(from._internal_as_double());
      break;
    }
    case kAsString: {
      _internal_set_as_string(from._internal_as_string());
      break;
    }
    case VALUE_NOT_SET: {
      break;
    }
  }
}

void CSceneObjectChange_Attribute::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tdrp.packet.CSceneObjectChange.Attribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSceneObjectChange_Attribute::CopyFrom(const CSceneObjectChange_Attribute& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tdrp.packet.CSceneObjectChange.Attribute)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSceneObjectChange_Attribute::IsInitialized() const {
  return true;
}

void CSceneObjectChange_Attribute::InternalSwap(CSceneObjectChange_Attribute* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  swap(id_, other->id_);
  swap(value_, other->value_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
}

::PROTOBUF_NAMESPACE_ID::Metadata CSceneObjectChange_Attribute::GetMetadata() const {
  return GetMetadataStatic();
}


// ===================================================================

class CSceneObjectChange::_Internal {
 public:
};

CSceneObjectChange::CSceneObjectChange(::PROTOBUF_NAMESPACE_ID::Arena* arena)
  : ::PROTOBUF_NAMESPACE_ID::Message(arena),
  properties_(arena),
  attributes_(arena) {
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tdrp.packet.CSceneObjectChange)
}
CSceneObjectChange::CSceneObjectChange(const CSceneObjectChange& from)
  : ::PROTOBUF_NAMESPACE_ID::Message(),
      properties_(from.properties_),
      attributes_(from.attributes_) {
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  id_ = from.id_;
  // @@protoc_insertion_point(copy_constructor:tdrp.packet.CSceneObjectChange)
}

void CSceneObjectChange::SharedCtor() {
id_ = 0u;
}

CSceneObjectChange::~CSceneObjectChange() {
  // @@protoc_insertion_point(destructor:tdrp.packet.CSceneObjectChange)
  SharedDtor();
  _internal_metadata_.Delete<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

void CSceneObjectChange::SharedDtor() {
  GOOGLE_DCHECK(GetArena() == nullptr);
}

void CSceneObjectChange::ArenaDtor(void* object) {
  CSceneObjectChange* _this = reinterpret_cast< CSceneObjectChange* >(object);
  (void)_this;
}
void CSceneObjectChange::RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena*) {
}
void CSceneObjectChange::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}

void CSceneObjectChange::Clear() {
// @@protoc_insertion_point(message_clear_start:tdrp.packet.CSceneObjectChange)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  properties_.Clear();
  attributes_.Clear();
  id_ = 0u;
  _internal_metadata_.Clear<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
}

const char* CSceneObjectChange::_InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) {
#define CHK_(x) if (PROTOBUF_PREDICT_FALSE(!(x))) goto failure
  while (!ctx->Done(&ptr)) {
    ::PROTOBUF_NAMESPACE_ID::uint32 tag;
    ptr = ::PROTOBUF_NAMESPACE_ID::internal::ReadTag(ptr, &tag);
    CHK_(ptr);
    switch (tag >> 3) {
      // fixed32 id = 1;
      case 1:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 13)) {
          id_ = ::PROTOBUF_NAMESPACE_ID::internal::UnalignedLoad<::PROTOBUF_NAMESPACE_ID::uint32>(ptr);
          ptr += sizeof(::PROTOBUF_NAMESPACE_ID::uint32);
        } else goto handle_unusual;
        continue;
      // repeated .tdrp.packet.CSceneObjectChange.Attribute properties = 2;
      case 2:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 18)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_properties(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<18>(ptr));
        } else goto handle_unusual;
        continue;
      // repeated .tdrp.packet.CSceneObjectChange.Attribute attributes = 3;
      case 3:
        if (PROTOBUF_PREDICT_TRUE(static_cast<::PROTOBUF_NAMESPACE_ID::uint8>(tag) == 26)) {
          ptr -= 1;
          do {
            ptr += 1;
            ptr = ctx->ParseMessage(_internal_add_attributes(), ptr);
            CHK_(ptr);
            if (!ctx->DataAvailable(ptr)) break;
          } while (::PROTOBUF_NAMESPACE_ID::internal::ExpectTag<26>(ptr));
        } else goto handle_unusual;
        continue;
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->SetLastTag(tag);
          goto success;
        }
        ptr = UnknownFieldParse(tag,
            _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(),
            ptr, ctx);
        CHK_(ptr != nullptr);
        continue;
      }
    }  // switch
  }  // while
success:
  return ptr;
failure:
  ptr = nullptr;
  goto success;
#undef CHK_
}

::PROTOBUF_NAMESPACE_ID::uint8* CSceneObjectChange::_InternalSerialize(
    ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:tdrp.packet.CSceneObjectChange)
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // fixed32 id = 1;
  if (this->id() != 0) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::WriteFixed32ToArray(1, this->_internal_id(), target);
  }

  // repeated .tdrp.packet.CSceneObjectChange.Attribute properties = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_properties_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(2, this->_internal_properties(i), target, stream);
  }

  // repeated .tdrp.packet.CSceneObjectChange.Attribute attributes = 3;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->_internal_attributes_size()); i < n; i++) {
    target = stream->EnsureSpace(target);
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::
      InternalWriteMessage(3, this->_internal_attributes(i), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target = ::PROTOBUF_NAMESPACE_ID::internal::WireFormat::InternalSerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tdrp.packet.CSceneObjectChange)
  return target;
}

size_t CSceneObjectChange::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tdrp.packet.CSceneObjectChange)
  size_t total_size = 0;

  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .tdrp.packet.CSceneObjectChange.Attribute properties = 2;
  total_size += 1UL * this->_internal_properties_size();
  for (const auto& msg : this->properties_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // repeated .tdrp.packet.CSceneObjectChange.Attribute attributes = 3;
  total_size += 1UL * this->_internal_attributes_size();
  for (const auto& msg : this->attributes_) {
    total_size +=
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::MessageSize(msg);
  }

  // fixed32 id = 1;
  if (this->id() != 0) {
    total_size += 1 + 4;
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    return ::PROTOBUF_NAMESPACE_ID::internal::ComputeUnknownFieldsSize(
        _internal_metadata_, total_size, &_cached_size_);
  }
  int cached_size = ::PROTOBUF_NAMESPACE_ID::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void CSceneObjectChange::MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tdrp.packet.CSceneObjectChange)
  GOOGLE_DCHECK_NE(&from, this);
  const CSceneObjectChange* source =
      ::PROTOBUF_NAMESPACE_ID::DynamicCastToGenerated<CSceneObjectChange>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tdrp.packet.CSceneObjectChange)
    ::PROTOBUF_NAMESPACE_ID::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tdrp.packet.CSceneObjectChange)
    MergeFrom(*source);
  }
}

void CSceneObjectChange::MergeFrom(const CSceneObjectChange& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tdrp.packet.CSceneObjectChange)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(from._internal_metadata_);
  ::PROTOBUF_NAMESPACE_ID::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  properties_.MergeFrom(from.properties_);
  attributes_.MergeFrom(from.attributes_);
  if (from.id() != 0) {
    _internal_set_id(from._internal_id());
  }
}

void CSceneObjectChange::CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tdrp.packet.CSceneObjectChange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CSceneObjectChange::CopyFrom(const CSceneObjectChange& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tdrp.packet.CSceneObjectChange)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool CSceneObjectChange::IsInitialized() const {
  return true;
}

void CSceneObjectChange::InternalSwap(CSceneObjectChange* other) {
  using std::swap;
  _internal_metadata_.Swap<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(&other->_internal_metadata_);
  properties_.InternalSwap(&other->properties_);
  attributes_.InternalSwap(&other->attributes_);
  swap(id_, other->id_);
}

::PROTOBUF_NAMESPACE_ID::Metadata CSceneObjectChange::GetMetadata() const {
  return GetMetadataStatic();
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
}  // namespace tdrp
PROTOBUF_NAMESPACE_OPEN
template<> PROTOBUF_NOINLINE ::tdrp::packet::CSceneObjectChange_Attribute* Arena::CreateMaybeMessage< ::tdrp::packet::CSceneObjectChange_Attribute >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tdrp::packet::CSceneObjectChange_Attribute >(arena);
}
template<> PROTOBUF_NOINLINE ::tdrp::packet::CSceneObjectChange* Arena::CreateMaybeMessage< ::tdrp::packet::CSceneObjectChange >(Arena* arena) {
  return Arena::CreateMessageInternal< ::tdrp::packet::CSceneObjectChange >(arena);
}
PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
