// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SClass.proto

#ifndef PROTOBUF_SClass_2eproto__INCLUDED
#define PROTOBUF_SClass_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_SClass_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[2];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSClass_AttributeImpl();
void InitDefaultsSClass_Attribute();
void InitDefaultsSClassImpl();
void InitDefaultsSClass();
inline void InitDefaults() {
  InitDefaultsSClass_Attribute();
  InitDefaultsSClass();
}
}  // namespace protobuf_SClass_2eproto
namespace tdrp {
namespace packet {
class SClass;
class SClassDefaultTypeInternal;
extern SClassDefaultTypeInternal _SClass_default_instance_;
class SClass_Attribute;
class SClass_AttributeDefaultTypeInternal;
extern SClass_AttributeDefaultTypeInternal _SClass_Attribute_default_instance_;
}  // namespace packet
}  // namespace tdrp
namespace tdrp {
namespace packet {

// ===================================================================

class SClass_Attribute : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tdrp.packet.SClass.Attribute) */ {
 public:
  SClass_Attribute();
  virtual ~SClass_Attribute();

  SClass_Attribute(const SClass_Attribute& from);

  inline SClass_Attribute& operator=(const SClass_Attribute& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SClass_Attribute(SClass_Attribute&& from) noexcept
    : SClass_Attribute() {
    *this = ::std::move(from);
  }

  inline SClass_Attribute& operator=(SClass_Attribute&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SClass_Attribute& default_instance();

  enum ValueCase {
    kAsInt = 3,
    kAsUint = 4,
    kAsFloat = 5,
    kAsDouble = 6,
    kAsString = 7,
    VALUE_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SClass_Attribute* internal_default_instance() {
    return reinterpret_cast<const SClass_Attribute*>(
               &_SClass_Attribute_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SClass_Attribute* other);
  friend void swap(SClass_Attribute& a, SClass_Attribute& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SClass_Attribute* New() const PROTOBUF_FINAL { return New(NULL); }

  SClass_Attribute* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SClass_Attribute& from);
  void MergeFrom(const SClass_Attribute& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SClass_Attribute* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string name = 2;
  void clear_name();
  static const int kNameFieldNumber = 2;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // uint32 id = 1;
  void clear_id();
  static const int kIdFieldNumber = 1;
  ::google::protobuf::uint32 id() const;
  void set_id(::google::protobuf::uint32 value);

  // int64 as_int = 3;
  private:
  bool has_as_int() const;
  public:
  void clear_as_int();
  static const int kAsIntFieldNumber = 3;
  ::google::protobuf::int64 as_int() const;
  void set_as_int(::google::protobuf::int64 value);

  // uint64 as_uint = 4;
  private:
  bool has_as_uint() const;
  public:
  void clear_as_uint();
  static const int kAsUintFieldNumber = 4;
  ::google::protobuf::uint64 as_uint() const;
  void set_as_uint(::google::protobuf::uint64 value);

  // float as_float = 5;
  private:
  bool has_as_float() const;
  public:
  void clear_as_float();
  static const int kAsFloatFieldNumber = 5;
  float as_float() const;
  void set_as_float(float value);

  // double as_double = 6;
  private:
  bool has_as_double() const;
  public:
  void clear_as_double();
  static const int kAsDoubleFieldNumber = 6;
  double as_double() const;
  void set_as_double(double value);

  // string as_string = 7;
  private:
  bool has_as_string() const;
  public:
  void clear_as_string();
  static const int kAsStringFieldNumber = 7;
  const ::std::string& as_string() const;
  void set_as_string(const ::std::string& value);
  #if LANG_CXX11
  void set_as_string(::std::string&& value);
  #endif
  void set_as_string(const char* value);
  void set_as_string(const char* value, size_t size);
  ::std::string* mutable_as_string();
  ::std::string* release_as_string();
  void set_allocated_as_string(::std::string* as_string);

  ValueCase value_case() const;
  // @@protoc_insertion_point(class_scope:tdrp.packet.SClass.Attribute)
 private:
  void set_has_as_int();
  void set_has_as_uint();
  void set_has_as_float();
  void set_has_as_double();
  void set_has_as_string();

  inline bool has_value() const;
  void clear_value();
  inline void clear_has_value();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::uint32 id_;
  union ValueUnion {
    ValueUnion() {}
    ::google::protobuf::int64 as_int_;
    ::google::protobuf::uint64 as_uint_;
    float as_float_;
    double as_double_;
    ::google::protobuf::internal::ArenaStringPtr as_string_;
  } value_;
  mutable int _cached_size_;
  ::google::protobuf::uint32 _oneof_case_[1];

  friend struct ::protobuf_SClass_2eproto::TableStruct;
  friend void ::protobuf_SClass_2eproto::InitDefaultsSClass_AttributeImpl();
};
// -------------------------------------------------------------------

class SClass : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tdrp.packet.SClass) */ {
 public:
  SClass();
  virtual ~SClass();

  SClass(const SClass& from);

  inline SClass& operator=(const SClass& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SClass(SClass&& from) noexcept
    : SClass() {
    *this = ::std::move(from);
  }

  inline SClass& operator=(SClass&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SClass& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SClass* internal_default_instance() {
    return reinterpret_cast<const SClass*>(
               &_SClass_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    1;

  void Swap(SClass* other);
  friend void swap(SClass& a, SClass& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SClass* New() const PROTOBUF_FINAL { return New(NULL); }

  SClass* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SClass& from);
  void MergeFrom(const SClass& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SClass* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  typedef SClass_Attribute Attribute;

  // accessors -------------------------------------------------------

  // repeated .tdrp.packet.SClass.Attribute attributes = 4;
  int attributes_size() const;
  void clear_attributes();
  static const int kAttributesFieldNumber = 4;
  const ::tdrp::packet::SClass_Attribute& attributes(int index) const;
  ::tdrp::packet::SClass_Attribute* mutable_attributes(int index);
  ::tdrp::packet::SClass_Attribute* add_attributes();
  ::google::protobuf::RepeatedPtrField< ::tdrp::packet::SClass_Attribute >*
      mutable_attributes();
  const ::google::protobuf::RepeatedPtrField< ::tdrp::packet::SClass_Attribute >&
      attributes() const;

  // string name = 1;
  void clear_name();
  static const int kNameFieldNumber = 1;
  const ::std::string& name() const;
  void set_name(const ::std::string& value);
  #if LANG_CXX11
  void set_name(::std::string&& value);
  #endif
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  ::std::string* mutable_name();
  ::std::string* release_name();
  void set_allocated_name(::std::string* name);

  // string scriptclient = 2;
  void clear_scriptclient();
  static const int kScriptclientFieldNumber = 2;
  const ::std::string& scriptclient() const;
  void set_scriptclient(const ::std::string& value);
  #if LANG_CXX11
  void set_scriptclient(::std::string&& value);
  #endif
  void set_scriptclient(const char* value);
  void set_scriptclient(const char* value, size_t size);
  ::std::string* mutable_scriptclient();
  ::std::string* release_scriptclient();
  void set_allocated_scriptclient(::std::string* scriptclient);

  // string scriptserver = 3;
  void clear_scriptserver();
  static const int kScriptserverFieldNumber = 3;
  const ::std::string& scriptserver() const;
  void set_scriptserver(const ::std::string& value);
  #if LANG_CXX11
  void set_scriptserver(::std::string&& value);
  #endif
  void set_scriptserver(const char* value);
  void set_scriptserver(const char* value, size_t size);
  ::std::string* mutable_scriptserver();
  ::std::string* release_scriptserver();
  void set_allocated_scriptserver(::std::string* scriptserver);

  // @@protoc_insertion_point(class_scope:tdrp.packet.SClass)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::RepeatedPtrField< ::tdrp::packet::SClass_Attribute > attributes_;
  ::google::protobuf::internal::ArenaStringPtr name_;
  ::google::protobuf::internal::ArenaStringPtr scriptclient_;
  ::google::protobuf::internal::ArenaStringPtr scriptserver_;
  mutable int _cached_size_;
  friend struct ::protobuf_SClass_2eproto::TableStruct;
  friend void ::protobuf_SClass_2eproto::InitDefaultsSClassImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SClass_Attribute

// uint32 id = 1;
inline void SClass_Attribute::clear_id() {
  id_ = 0u;
}
inline ::google::protobuf::uint32 SClass_Attribute::id() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.id)
  return id_;
}
inline void SClass_Attribute::set_id(::google::protobuf::uint32 value) {
  
  id_ = value;
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.id)
}

// string name = 2;
inline void SClass_Attribute::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SClass_Attribute::name() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.name)
  return name_.GetNoArena();
}
inline void SClass_Attribute::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.name)
}
#if LANG_CXX11
inline void SClass_Attribute::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tdrp.packet.SClass.Attribute.name)
}
#endif
inline void SClass_Attribute::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tdrp.packet.SClass.Attribute.name)
}
inline void SClass_Attribute::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tdrp.packet.SClass.Attribute.name)
}
inline ::std::string* SClass_Attribute::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SClass.Attribute.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SClass_Attribute::release_name() {
  // @@protoc_insertion_point(field_release:tdrp.packet.SClass.Attribute.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SClass_Attribute::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tdrp.packet.SClass.Attribute.name)
}

// int64 as_int = 3;
inline bool SClass_Attribute::has_as_int() const {
  return value_case() == kAsInt;
}
inline void SClass_Attribute::set_has_as_int() {
  _oneof_case_[0] = kAsInt;
}
inline void SClass_Attribute::clear_as_int() {
  if (has_as_int()) {
    value_.as_int_ = GOOGLE_LONGLONG(0);
    clear_has_value();
  }
}
inline ::google::protobuf::int64 SClass_Attribute::as_int() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.as_int)
  if (has_as_int()) {
    return value_.as_int_;
  }
  return GOOGLE_LONGLONG(0);
}
inline void SClass_Attribute::set_as_int(::google::protobuf::int64 value) {
  if (!has_as_int()) {
    clear_value();
    set_has_as_int();
  }
  value_.as_int_ = value;
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_int)
}

// uint64 as_uint = 4;
inline bool SClass_Attribute::has_as_uint() const {
  return value_case() == kAsUint;
}
inline void SClass_Attribute::set_has_as_uint() {
  _oneof_case_[0] = kAsUint;
}
inline void SClass_Attribute::clear_as_uint() {
  if (has_as_uint()) {
    value_.as_uint_ = GOOGLE_ULONGLONG(0);
    clear_has_value();
  }
}
inline ::google::protobuf::uint64 SClass_Attribute::as_uint() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.as_uint)
  if (has_as_uint()) {
    return value_.as_uint_;
  }
  return GOOGLE_ULONGLONG(0);
}
inline void SClass_Attribute::set_as_uint(::google::protobuf::uint64 value) {
  if (!has_as_uint()) {
    clear_value();
    set_has_as_uint();
  }
  value_.as_uint_ = value;
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_uint)
}

// float as_float = 5;
inline bool SClass_Attribute::has_as_float() const {
  return value_case() == kAsFloat;
}
inline void SClass_Attribute::set_has_as_float() {
  _oneof_case_[0] = kAsFloat;
}
inline void SClass_Attribute::clear_as_float() {
  if (has_as_float()) {
    value_.as_float_ = 0;
    clear_has_value();
  }
}
inline float SClass_Attribute::as_float() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.as_float)
  if (has_as_float()) {
    return value_.as_float_;
  }
  return 0;
}
inline void SClass_Attribute::set_as_float(float value) {
  if (!has_as_float()) {
    clear_value();
    set_has_as_float();
  }
  value_.as_float_ = value;
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_float)
}

// double as_double = 6;
inline bool SClass_Attribute::has_as_double() const {
  return value_case() == kAsDouble;
}
inline void SClass_Attribute::set_has_as_double() {
  _oneof_case_[0] = kAsDouble;
}
inline void SClass_Attribute::clear_as_double() {
  if (has_as_double()) {
    value_.as_double_ = 0;
    clear_has_value();
  }
}
inline double SClass_Attribute::as_double() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.as_double)
  if (has_as_double()) {
    return value_.as_double_;
  }
  return 0;
}
inline void SClass_Attribute::set_as_double(double value) {
  if (!has_as_double()) {
    clear_value();
    set_has_as_double();
  }
  value_.as_double_ = value;
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_double)
}

// string as_string = 7;
inline bool SClass_Attribute::has_as_string() const {
  return value_case() == kAsString;
}
inline void SClass_Attribute::set_has_as_string() {
  _oneof_case_[0] = kAsString;
}
inline void SClass_Attribute::clear_as_string() {
  if (has_as_string()) {
    value_.as_string_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
    clear_has_value();
  }
}
inline const ::std::string& SClass_Attribute::as_string() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.Attribute.as_string)
  if (has_as_string()) {
    return value_.as_string_.GetNoArena();
  }
  return *&::google::protobuf::internal::GetEmptyStringAlreadyInited();
}
inline void SClass_Attribute::set_as_string(const ::std::string& value) {
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_string)
  if (!has_as_string()) {
    clear_value();
    set_has_as_string();
    value_.as_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.as_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_string)
}
#if LANG_CXX11
inline void SClass_Attribute::set_as_string(::std::string&& value) {
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.Attribute.as_string)
  if (!has_as_string()) {
    clear_value();
    set_has_as_string();
    value_.as_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.as_string_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tdrp.packet.SClass.Attribute.as_string)
}
#endif
inline void SClass_Attribute::set_as_string(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  if (!has_as_string()) {
    clear_value();
    set_has_as_string();
    value_.as_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.as_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tdrp.packet.SClass.Attribute.as_string)
}
inline void SClass_Attribute::set_as_string(const char* value, size_t size) {
  if (!has_as_string()) {
    clear_value();
    set_has_as_string();
    value_.as_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  value_.as_string_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tdrp.packet.SClass.Attribute.as_string)
}
inline ::std::string* SClass_Attribute::mutable_as_string() {
  if (!has_as_string()) {
    clear_value();
    set_has_as_string();
    value_.as_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SClass.Attribute.as_string)
  return value_.as_string_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SClass_Attribute::release_as_string() {
  // @@protoc_insertion_point(field_release:tdrp.packet.SClass.Attribute.as_string)
  if (has_as_string()) {
    clear_has_value();
    return value_.as_string_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  } else {
    return NULL;
  }
}
inline void SClass_Attribute::set_allocated_as_string(::std::string* as_string) {
  if (!has_as_string()) {
    value_.as_string_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  }
  clear_value();
  if (as_string != NULL) {
    set_has_as_string();
    value_.as_string_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
        as_string);
  }
  // @@protoc_insertion_point(field_set_allocated:tdrp.packet.SClass.Attribute.as_string)
}

inline bool SClass_Attribute::has_value() const {
  return value_case() != VALUE_NOT_SET;
}
inline void SClass_Attribute::clear_has_value() {
  _oneof_case_[0] = VALUE_NOT_SET;
}
inline SClass_Attribute::ValueCase SClass_Attribute::value_case() const {
  return SClass_Attribute::ValueCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// SClass

// string name = 1;
inline void SClass::clear_name() {
  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SClass::name() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.name)
  return name_.GetNoArena();
}
inline void SClass::set_name(const ::std::string& value) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.name)
}
#if LANG_CXX11
inline void SClass::set_name(::std::string&& value) {
  
  name_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tdrp.packet.SClass.name)
}
#endif
inline void SClass::set_name(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tdrp.packet.SClass.name)
}
inline void SClass::set_name(const char* value, size_t size) {
  
  name_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tdrp.packet.SClass.name)
}
inline ::std::string* SClass::mutable_name() {
  
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SClass.name)
  return name_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SClass::release_name() {
  // @@protoc_insertion_point(field_release:tdrp.packet.SClass.name)
  
  return name_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SClass::set_allocated_name(::std::string* name) {
  if (name != NULL) {
    
  } else {
    
  }
  name_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), name);
  // @@protoc_insertion_point(field_set_allocated:tdrp.packet.SClass.name)
}

// string scriptclient = 2;
inline void SClass::clear_scriptclient() {
  scriptclient_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SClass::scriptclient() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.scriptclient)
  return scriptclient_.GetNoArena();
}
inline void SClass::set_scriptclient(const ::std::string& value) {
  
  scriptclient_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.scriptclient)
}
#if LANG_CXX11
inline void SClass::set_scriptclient(::std::string&& value) {
  
  scriptclient_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tdrp.packet.SClass.scriptclient)
}
#endif
inline void SClass::set_scriptclient(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  scriptclient_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tdrp.packet.SClass.scriptclient)
}
inline void SClass::set_scriptclient(const char* value, size_t size) {
  
  scriptclient_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tdrp.packet.SClass.scriptclient)
}
inline ::std::string* SClass::mutable_scriptclient() {
  
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SClass.scriptclient)
  return scriptclient_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SClass::release_scriptclient() {
  // @@protoc_insertion_point(field_release:tdrp.packet.SClass.scriptclient)
  
  return scriptclient_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SClass::set_allocated_scriptclient(::std::string* scriptclient) {
  if (scriptclient != NULL) {
    
  } else {
    
  }
  scriptclient_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), scriptclient);
  // @@protoc_insertion_point(field_set_allocated:tdrp.packet.SClass.scriptclient)
}

// string scriptserver = 3;
inline void SClass::clear_scriptserver() {
  scriptserver_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SClass::scriptserver() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.scriptserver)
  return scriptserver_.GetNoArena();
}
inline void SClass::set_scriptserver(const ::std::string& value) {
  
  scriptserver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SClass.scriptserver)
}
#if LANG_CXX11
inline void SClass::set_scriptserver(::std::string&& value) {
  
  scriptserver_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tdrp.packet.SClass.scriptserver)
}
#endif
inline void SClass::set_scriptserver(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  scriptserver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tdrp.packet.SClass.scriptserver)
}
inline void SClass::set_scriptserver(const char* value, size_t size) {
  
  scriptserver_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tdrp.packet.SClass.scriptserver)
}
inline ::std::string* SClass::mutable_scriptserver() {
  
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SClass.scriptserver)
  return scriptserver_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SClass::release_scriptserver() {
  // @@protoc_insertion_point(field_release:tdrp.packet.SClass.scriptserver)
  
  return scriptserver_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SClass::set_allocated_scriptserver(::std::string* scriptserver) {
  if (scriptserver != NULL) {
    
  } else {
    
  }
  scriptserver_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), scriptserver);
  // @@protoc_insertion_point(field_set_allocated:tdrp.packet.SClass.scriptserver)
}

// repeated .tdrp.packet.SClass.Attribute attributes = 4;
inline int SClass::attributes_size() const {
  return attributes_.size();
}
inline void SClass::clear_attributes() {
  attributes_.Clear();
}
inline const ::tdrp::packet::SClass_Attribute& SClass::attributes(int index) const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SClass.attributes)
  return attributes_.Get(index);
}
inline ::tdrp::packet::SClass_Attribute* SClass::mutable_attributes(int index) {
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SClass.attributes)
  return attributes_.Mutable(index);
}
inline ::tdrp::packet::SClass_Attribute* SClass::add_attributes() {
  // @@protoc_insertion_point(field_add:tdrp.packet.SClass.attributes)
  return attributes_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::tdrp::packet::SClass_Attribute >*
SClass::mutable_attributes() {
  // @@protoc_insertion_point(field_mutable_list:tdrp.packet.SClass.attributes)
  return &attributes_;
}
inline const ::google::protobuf::RepeatedPtrField< ::tdrp::packet::SClass_Attribute >&
SClass::attributes() const {
  // @@protoc_insertion_point(field_list:tdrp.packet.SClass.attributes)
  return attributes_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace packet
}  // namespace tdrp

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SClass_2eproto__INCLUDED
