// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SLoginStatus.proto

#ifndef PROTOBUF_SLoginStatus_2eproto__INCLUDED
#define PROTOBUF_SLoginStatus_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_SLoginStatus_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsSLoginStatusImpl();
void InitDefaultsSLoginStatus();
inline void InitDefaults() {
  InitDefaultsSLoginStatus();
}
}  // namespace protobuf_SLoginStatus_2eproto
namespace tdrp {
namespace packet {
class SLoginStatus;
class SLoginStatusDefaultTypeInternal;
extern SLoginStatusDefaultTypeInternal _SLoginStatus_default_instance_;
}  // namespace packet
}  // namespace tdrp
namespace tdrp {
namespace packet {

// ===================================================================

class SLoginStatus : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tdrp.packet.SLoginStatus) */ {
 public:
  SLoginStatus();
  virtual ~SLoginStatus();

  SLoginStatus(const SLoginStatus& from);

  inline SLoginStatus& operator=(const SLoginStatus& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  SLoginStatus(SLoginStatus&& from) noexcept
    : SLoginStatus() {
    *this = ::std::move(from);
  }

  inline SLoginStatus& operator=(SLoginStatus&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  static const ::google::protobuf::Descriptor* descriptor();
  static const SLoginStatus& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const SLoginStatus* internal_default_instance() {
    return reinterpret_cast<const SLoginStatus*>(
               &_SLoginStatus_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(SLoginStatus* other);
  friend void swap(SLoginStatus& a, SLoginStatus& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline SLoginStatus* New() const PROTOBUF_FINAL { return New(NULL); }

  SLoginStatus* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const SLoginStatus& from);
  void MergeFrom(const SLoginStatus& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(SLoginStatus* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // string message = 2;
  void clear_message();
  static const int kMessageFieldNumber = 2;
  const ::std::string& message() const;
  void set_message(const ::std::string& value);
  #if LANG_CXX11
  void set_message(::std::string&& value);
  #endif
  void set_message(const char* value);
  void set_message(const char* value, size_t size);
  ::std::string* mutable_message();
  ::std::string* release_message();
  void set_allocated_message(::std::string* message);

  // bool success = 1;
  void clear_success();
  static const int kSuccessFieldNumber = 1;
  bool success() const;
  void set_success(bool value);

  // @@protoc_insertion_point(class_scope:tdrp.packet.SLoginStatus)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::ArenaStringPtr message_;
  bool success_;
  mutable int _cached_size_;
  friend struct ::protobuf_SLoginStatus_2eproto::TableStruct;
  friend void ::protobuf_SLoginStatus_2eproto::InitDefaultsSLoginStatusImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SLoginStatus

// bool success = 1;
inline void SLoginStatus::clear_success() {
  success_ = false;
}
inline bool SLoginStatus::success() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SLoginStatus.success)
  return success_;
}
inline void SLoginStatus::set_success(bool value) {
  
  success_ = value;
  // @@protoc_insertion_point(field_set:tdrp.packet.SLoginStatus.success)
}

// string message = 2;
inline void SLoginStatus::clear_message() {
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline const ::std::string& SLoginStatus::message() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SLoginStatus.message)
  return message_.GetNoArena();
}
inline void SLoginStatus::set_message(const ::std::string& value) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SLoginStatus.message)
}
#if LANG_CXX11
inline void SLoginStatus::set_message(::std::string&& value) {
  
  message_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:tdrp.packet.SLoginStatus.message)
}
#endif
inline void SLoginStatus::set_message(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:tdrp.packet.SLoginStatus.message)
}
inline void SLoginStatus::set_message(const char* value, size_t size) {
  
  message_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:tdrp.packet.SLoginStatus.message)
}
inline ::std::string* SLoginStatus::mutable_message() {
  
  // @@protoc_insertion_point(field_mutable:tdrp.packet.SLoginStatus.message)
  return message_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* SLoginStatus::release_message() {
  // @@protoc_insertion_point(field_release:tdrp.packet.SLoginStatus.message)
  
  return message_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void SLoginStatus::set_allocated_message(::std::string* message) {
  if (message != NULL) {
    
  } else {
    
  }
  message_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), message);
  // @@protoc_insertion_point(field_set_allocated:tdrp.packet.SLoginStatus.message)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace packet
}  // namespace tdrp

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_SLoginStatus_2eproto__INCLUDED
