// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SSceneObjectControl.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_SSceneObjectControl_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_SSceneObjectControl_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3015000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3015006 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_SSceneObjectControl_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_SSceneObjectControl_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_SSceneObjectControl_2eproto;
::PROTOBUF_NAMESPACE_ID::Metadata descriptor_table_SSceneObjectControl_2eproto_metadata_getter(int index);
namespace tdrp {
namespace packet {
class SSceneObjectControl;
struct SSceneObjectControlDefaultTypeInternal;
extern SSceneObjectControlDefaultTypeInternal _SSceneObjectControl_default_instance_;
}  // namespace packet
}  // namespace tdrp
PROTOBUF_NAMESPACE_OPEN
template<> ::tdrp::packet::SSceneObjectControl* Arena::CreateMaybeMessage<::tdrp::packet::SSceneObjectControl>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace tdrp {
namespace packet {

// ===================================================================

class SSceneObjectControl PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:tdrp.packet.SSceneObjectControl) */ {
 public:
  inline SSceneObjectControl() : SSceneObjectControl(nullptr) {}
  virtual ~SSceneObjectControl();
  explicit constexpr SSceneObjectControl(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SSceneObjectControl(const SSceneObjectControl& from);
  SSceneObjectControl(SSceneObjectControl&& from) noexcept
    : SSceneObjectControl() {
    *this = ::std::move(from);
  }

  inline SSceneObjectControl& operator=(const SSceneObjectControl& from) {
    CopyFrom(from);
    return *this;
  }
  inline SSceneObjectControl& operator=(SSceneObjectControl&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const SSceneObjectControl& default_instance() {
    return *internal_default_instance();
  }
  static inline const SSceneObjectControl* internal_default_instance() {
    return reinterpret_cast<const SSceneObjectControl*>(
               &_SSceneObjectControl_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SSceneObjectControl& a, SSceneObjectControl& b) {
    a.Swap(&b);
  }
  inline void Swap(SSceneObjectControl* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SSceneObjectControl* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SSceneObjectControl* New() const final {
    return CreateMaybeMessage<SSceneObjectControl>(nullptr);
  }

  SSceneObjectControl* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SSceneObjectControl>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const SSceneObjectControl& from);
  void MergeFrom(const SSceneObjectControl& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SSceneObjectControl* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "tdrp.packet.SSceneObjectControl";
  }
  protected:
  explicit SSceneObjectControl(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    return ::descriptor_table_SSceneObjectControl_2eproto_metadata_getter(kIndexInFileMessages);
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOldIdFieldNumber = 1,
    kNewIdFieldNumber = 2,
  };
  // fixed32 old_id = 1;
  void clear_old_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 old_id() const;
  void set_old_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_old_id() const;
  void _internal_set_old_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // fixed32 new_id = 2;
  void clear_new_id();
  ::PROTOBUF_NAMESPACE_ID::uint32 new_id() const;
  void set_new_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_new_id() const;
  void _internal_set_new_id(::PROTOBUF_NAMESPACE_ID::uint32 value);
  public:

  // @@protoc_insertion_point(class_scope:tdrp.packet.SSceneObjectControl)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::uint32 old_id_;
  ::PROTOBUF_NAMESPACE_ID::uint32 new_id_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_SSceneObjectControl_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SSceneObjectControl

// fixed32 old_id = 1;
inline void SSceneObjectControl::clear_old_id() {
  old_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSceneObjectControl::_internal_old_id() const {
  return old_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSceneObjectControl::old_id() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SSceneObjectControl.old_id)
  return _internal_old_id();
}
inline void SSceneObjectControl::_internal_set_old_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  old_id_ = value;
}
inline void SSceneObjectControl::set_old_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_old_id(value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SSceneObjectControl.old_id)
}

// fixed32 new_id = 2;
inline void SSceneObjectControl::clear_new_id() {
  new_id_ = 0u;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSceneObjectControl::_internal_new_id() const {
  return new_id_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 SSceneObjectControl::new_id() const {
  // @@protoc_insertion_point(field_get:tdrp.packet.SSceneObjectControl.new_id)
  return _internal_new_id();
}
inline void SSceneObjectControl::_internal_set_new_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  
  new_id_ = value;
}
inline void SSceneObjectControl::set_new_id(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_set_new_id(value);
  // @@protoc_insertion_point(field_set:tdrp.packet.SSceneObjectControl.new_id)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace packet
}  // namespace tdrp

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_SSceneObjectControl_2eproto
