// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SSwitchScene.proto

#include "SSwitchScene.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace tdrp {
namespace packet {
class SSwitchSceneDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<SSwitchScene>
      _instance;
} _SSwitchScene_default_instance_;
}  // namespace packet
}  // namespace tdrp
namespace protobuf_SSwitchScene_2eproto {
void InitDefaultsSSwitchSceneImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tdrp::packet::_SSwitchScene_default_instance_;
    new (ptr) ::tdrp::packet::SSwitchScene();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tdrp::packet::SSwitchScene::InitAsDefaultInstance();
}

void InitDefaultsSSwitchScene() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &InitDefaultsSSwitchSceneImpl);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdrp::packet::SSwitchScene, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tdrp::packet::SSwitchScene, scene_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tdrp::packet::SSwitchScene)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::tdrp::packet::_SSwitchScene_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "SSwitchScene.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\022SSwitchScene.proto\022\013tdrp.packet\"\035\n\014SSw"
      "itchScene\022\r\n\005scene\030\001 \001(\tb\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 72);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "SSwitchScene.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_SSwitchScene_2eproto
namespace tdrp {
namespace packet {

// ===================================================================

void SSwitchScene::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int SSwitchScene::kSceneFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

SSwitchScene::SSwitchScene()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_SSwitchScene_2eproto::InitDefaultsSSwitchScene();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tdrp.packet.SSwitchScene)
}
SSwitchScene::SSwitchScene(const SSwitchScene& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  scene_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.scene().size() > 0) {
    scene_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.scene_);
  }
  // @@protoc_insertion_point(copy_constructor:tdrp.packet.SSwitchScene)
}

void SSwitchScene::SharedCtor() {
  scene_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

SSwitchScene::~SSwitchScene() {
  // @@protoc_insertion_point(destructor:tdrp.packet.SSwitchScene)
  SharedDtor();
}

void SSwitchScene::SharedDtor() {
  scene_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void SSwitchScene::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* SSwitchScene::descriptor() {
  ::protobuf_SSwitchScene_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_SSwitchScene_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const SSwitchScene& SSwitchScene::default_instance() {
  ::protobuf_SSwitchScene_2eproto::InitDefaultsSSwitchScene();
  return *internal_default_instance();
}

SSwitchScene* SSwitchScene::New(::google::protobuf::Arena* arena) const {
  SSwitchScene* n = new SSwitchScene;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void SSwitchScene::Clear() {
// @@protoc_insertion_point(message_clear_start:tdrp.packet.SSwitchScene)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  scene_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool SSwitchScene::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tdrp.packet.SSwitchScene)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string scene = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_scene()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->scene().data(), static_cast<int>(this->scene().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "tdrp.packet.SSwitchScene.scene"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tdrp.packet.SSwitchScene)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tdrp.packet.SSwitchScene)
  return false;
#undef DO_
}

void SSwitchScene::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tdrp.packet.SSwitchScene)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string scene = 1;
  if (this->scene().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->scene().data(), static_cast<int>(this->scene().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tdrp.packet.SSwitchScene.scene");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->scene(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tdrp.packet.SSwitchScene)
}

::google::protobuf::uint8* SSwitchScene::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tdrp.packet.SSwitchScene)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string scene = 1;
  if (this->scene().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->scene().data(), static_cast<int>(this->scene().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tdrp.packet.SSwitchScene.scene");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->scene(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tdrp.packet.SSwitchScene)
  return target;
}

size_t SSwitchScene::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tdrp.packet.SSwitchScene)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string scene = 1;
  if (this->scene().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->scene());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void SSwitchScene::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tdrp.packet.SSwitchScene)
  GOOGLE_DCHECK_NE(&from, this);
  const SSwitchScene* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const SSwitchScene>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tdrp.packet.SSwitchScene)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tdrp.packet.SSwitchScene)
    MergeFrom(*source);
  }
}

void SSwitchScene::MergeFrom(const SSwitchScene& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tdrp.packet.SSwitchScene)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.scene().size() > 0) {

    scene_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.scene_);
  }
}

void SSwitchScene::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tdrp.packet.SSwitchScene)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void SSwitchScene::CopyFrom(const SSwitchScene& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tdrp.packet.SSwitchScene)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool SSwitchScene::IsInitialized() const {
  return true;
}

void SSwitchScene::Swap(SSwitchScene* other) {
  if (other == this) return;
  InternalSwap(other);
}
void SSwitchScene::InternalSwap(SSwitchScene* other) {
  using std::swap;
  scene_.Swap(&other->scene_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata SSwitchScene::GetMetadata() const {
  protobuf_SSwitchScene_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_SSwitchScene_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace packet
}  // namespace tdrp

// @@protoc_insertion_point(global_scope)
